In [1]:
#NUMPY

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
# Array Creation 
a=np.array(10)
type(a)

numpy.ndarray

In [10]:
#Zero dimensial Array
z=np.array(10)
z.ndim

0

In [12]:
#1 dimensional array
b=np.array([10,11,12,13])
b.ndim

1

In [2]:
#2 dimensional array
c np.array ([[10,12,13,14,15]])
c.ndim

SyntaxError: invalid syntax (Temp/ipykernel_9160/3086055855.py, line 2)

In [10]:
#Change data type into other elements
a=np.array([10,15,20,25])
a.dtype


a=np.array([10,15,20,25],dtype='float')
print(a.dtype)
a

float64


array([10., 15., 20., 25.])

In [18]:
#Other ways of creating array

#1) Arrange
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
#2) Linspace
b=np.linspace(1,5,15)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [20]:
#Random
r=np.random.rand(5,5)
r

array([[0.79943048, 0.06380829, 0.35560816, 0.40399883, 0.32613735],
       [0.1898173 , 0.70386885, 0.00941435, 0.41726602, 0.17666116],
       [0.28235404, 0.9118813 , 0.70357745, 0.84091126, 0.64892406],
       [0.8745347 , 0.36711972, 0.04227342, 0.17657267, 0.87871809],
       [0.08051392, 0.37563651, 0.5864449 , 0.20903683, 0.41504256]])

In [21]:
R1=np.random.randint(5,size=10)
R1

array([0, 0, 0, 4, 0, 3, 1, 2, 2, 3])

In [15]:
#Slicing and indexing of an array
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a[1,2]

6

In [18]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a[0,1:]

array([2, 3])

In [20]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [21]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [23]:
#Reshaping  the arrays
a=np.random.rand(5,2)
a

array([[0.73450482, 0.9098575 ],
       [0.71505094, 0.03023201],
       [0.51399476, 0.08416185],
       [0.92352261, 0.2261553 ],
       [0.66287295, 0.79700742]])

In [24]:
a.reshape(2,5)

array([[0.73450482, 0.9098575 , 0.71505094, 0.03023201, 0.51399476],
       [0.08416185, 0.92352261, 0.2261553 , 0.66287295, 0.79700742]])

In [25]:
a.reshape(10,1)

array([[0.73450482],
       [0.9098575 ],
       [0.71505094],
       [0.03023201],
       [0.51399476],
       [0.08416185],
       [0.92352261],
       [0.2261553 ],
       [0.66287295],
       [0.79700742]])

In [26]:
a.reshape(1,10)

array([[0.73450482, 0.9098575 , 0.71505094, 0.03023201, 0.51399476,
        0.08416185, 0.92352261, 0.2261553 , 0.66287295, 0.79700742]])

In [27]:
a.reshape(5,-1)

array([[0.73450482, 0.9098575 ],
       [0.71505094, 0.03023201],
       [0.51399476, 0.08416185],
       [0.92352261, 0.2261553 ],
       [0.66287295, 0.79700742]])

In [30]:
a.reshape(5,-10)

array([[0.73450482, 0.9098575 ],
       [0.71505094, 0.03023201],
       [0.51399476, 0.08416185],
       [0.92352261, 0.2261553 ],
       [0.66287295, 0.79700742]])

In [31]:
#Agreegate function
a.min()

0.03023201108231055

In [32]:
a.std()

0.3156645669438821

In [33]:
a.var()

0.09964411882386864

In [34]:
#Staking
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [36]:
np.hstack([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])